name: HOPR Unit Tests

# Controls when the workflow will run
on:
  # Triggers the workflow on push events for all the branches
  push:
    branches: [ "**" ]

jobs:
  setup-runner:
    runs-on: ubuntu-latest
    strategy:
      # You can use PyPy versions in python-version.
      # For example, pypy2.7 and pypy3.9
      matrix:
        python-version: ["3.8"]

    steps:
      - uses: actions/checkout@master # THIS IS IMPORTANT
      - uses: actions/setup-python@v3 # THIS IS IMPORTANT
        with:
          python-version: '3.8'
      - name: Test
        uses: onichandame/python-test-action@master
        with:
          deps_list: 'requirements.txt'
      - name: Install Dependencies
        run: |
          python3 -m pip install --upgrade pip
          python3 -m pip install -r requirements.txt
          docker run --rm -d --network host --name pluto_cluster gcr.io/hoprassociation/hopr-pluto:1.92.7
      # Waiting until all the services are up (waiting for 5th node 200 response)
      - uses: nev7n/wait_for_response@v1
        with:
          url: 'http://localhost:13305/api/v2/_swagger'
          responseCode: 200
          timeout: 200000
          interval: 500
      - name: Lint with Ruff
        run: |
          ruff --format=github --target-version=py38 .
        continue-on-error: true
      - name: Show library versions
        run: pip show websocket-client
      - name: Run Unit Tests
        run: pytest -v tests_unit/
      - name: Run Integration Tests
        run: pytest -v tests_integration/
      - name: Run System Tests
        run: pytest -v tests_system/
      - name: Run End-to-End Tests
        run: pytest -v tests_e2e/