name: HOPR Unit Tests

# Controls when the workflow will run
on:
  # Triggers the workflow on push events for all the branches
  push:
    branches: [ "**" ]

jobs:
  unit-test-runner:
    runs-on: ubuntu-latest
    strategy:
      # You can use PyPy versions in python-version.
      # For example, pypy2.7 and pypy3.9
      matrix:
        python-version: ["3.8"]

    steps:
      - uses: actions/checkout@master # THIS IS IMPORTANT
      - uses: actions/setup-python@v3 # THIS IS IMPORTANT
        with:
          python-version: '3.8'
      - name: Test
        uses: onichandame/python-test-action@master
        with:
          deps_list: 'requirements.txt'
      - name: Install Dependencies
        run: |
          python3 -m pip install --upgrade pip
          python3 -m pip install -r requirements.txt
          docker run --rm -d --network host --name pluto_cluster gcr.io/hoprassociation/hopr-pluto:1.92.7
      - name: Lint with Ruff
        run: |
          ruff --format=github --target-version=py38 .
        continue-on-error: true
      - name: Show library versions
        run: |
          python3 --version
          pytest --version
          pip show requests
          pip show websockets
          pip show websocket-client
      - name: Wait for services to be available
        run: python3 wait_for_services.py
      - name: Run Unit Tests
        run: pytest -v tests_unit/
  
  integration-test-runner:
    runs-on: ubuntu-latest
    strategy:
      # You can use PyPy versions in python-version.
      # For example, pypy2.7 and pypy3.9
      matrix:
        python-version: ["3.8"]

    steps:
      - uses: actions/checkout@master # THIS IS IMPORTANT
      - uses: actions/setup-python@v3 # THIS IS IMPORTANT
        with:
          python-version: '3.8'
      - name: Test
        uses: onichandame/python-test-action@master
        with:
          deps_list: 'requirements.txt'
      - name: Install Dependencies
        run: |
          python3 -m pip install --upgrade pip
          python3 -m pip install -r requirements.txt
          docker run --rm -d --network host --name pluto_cluster gcr.io/hoprassociation/hopr-pluto:1.92.7
      - name: Lint with Ruff
        run: |
          ruff --format=github --target-version=py38 .
        continue-on-error: true
      - name: Show library versions
        run: |
          python3 --version
          pytest --version
          pip show requests
          pip show websockets
          pip show websocket-client
      - name: Wait for services to be available
        run: python3 wait_for_services.py
      - name: Run Unit Tests
        run: pytest -v tests_integration/