name: HOPR Unit Tests

# Controls when the workflow will run
on:
  # Triggers the workflow on push events for all the branches
  push:
    branches: [ "**" ]

jobs:
  setup-runner:
    runs-on: ubuntu-latest
    strategy:
      # You can use PyPy versions in python-version.
      # For example, pypy2.7 and pypy3.9
      matrix:
        python-version: ["3.11"]

    steps:
      - name: Install dependencies
        run: |
          pip3 install --upgrade pip3
          pip3 install -r requirements.txt
          docker run --rm -d --network host --name pluto_cluster gcr.io/hoprassociation/hopr-pluto:1.92.7
          docker logs -f pluto_cluster
          ./wait-for host:13305 -t 200
      - name: Lint with Ruff
        run: |
          ruff --format=github --target-version=py311 .
        continue-on-error: true
      - name: Run unit tests
        run: pytest -v tests_unit/